language: node_js
node_js:
- '12.13'
before_script:
- npm run lint
- npm run build
script:
- npm test -- --coverage
- npm run coveralls
after_success:
- npm pack
deploy:
  - provider: npm
    email: kbirger@gmail.com
    api_key:
      secure: dO2KMWqiCm+CSVvvbdvizLnKr70g/etkeC5xU19dttcvp9bWUMwayUXx0jeX/Z7ok1aXskPv1qhtsJtm9auk9+WvCiIUP8AvfCjCrnAN8MuYxXBBuetRL+99RvkJr/frBqoeO2OgKi/uRrwqld1bkX4rhBuEBXHBRbMpQokDmKt+ikYFLl0ZG+S5gPlykA1HjNMI72SgEQld0zYRDQmLBUQ0Tc4KAY2HARbYvzEVdzMOfRBVc7vUHcKqJ+9ZdsCSHKsKLoAB5dV9c9M/fQYAYJ0bU2h/HY7Nbo/F2s5bgQAT0vJPNd+xe83zPVuNTEbFrETotPO9qE7BxJ1JYX40iyilWjh1ymLvIuGbOfWyBKq/dofDTETptYAGflQ+GMedpmHZE8ygYY1WiP4r8jOF7H2IBcWfjmZHOOS4dvxX0wYzuK0PtZkZNMQj/lcX0ZYVte4HSYixsTTPbxhxZFNBJKWrWWc1nxjLBWdTUwFkcsXcENgCapNSAPCKGwzv2PZa+Q+tqatfCW/cSc5VgxHehCFp3QAKlAPkU0D7eQQtbxYwBgDpOkxZA27qxr7vV8WvmnK2UXLrYmyTtCBoqul4uGITU1zVXbuklDJZBoE83qHmYT5kr8P+uXyN+18BJV4baRAoS8T2HOrCAT0t/uovcNocZ2OOmW4GorOFZBnHhSk=
    on:
      tags: true
      repo: kbirger/reddit-notifier
    skip_cleanup: 'true'
  - provider: releases
    api_key:
      secure: lECaV/sEFhmtbXiAgejKe1FLTyLaVR0gNo6BwxaX2dSYeOTcQyZa/A3ScE6jeQm7IgbNP+Eux6cf8Rj/3ZSIqHLSKuo0BTPUKUFXinyNYLLlh5DuUGHkjnJPOAuz9Bjl+h2n84VbqdchTune9brkCgGljU7qLZmAPZ6i82vV8Z4JVOaftLXq4ucRQ5HbweGbEQonC6zCosE9KPvMCvXvsXcR9YpVpw6DDwXdPc6FJudkqO9AGDFwbUVDqNkeOacIdYISB0xMVd2NPAILM2oOQq6V1mUxImtDxD1yp+iICqo6lraEmgk9uUR6/fPEVOxnCkbhwhN/7bavBHY4RxJydu1b4FCOdZ+GlhcvPxoXfaMF8Fb3U4bEhlQx4MDkgiJO/5ayFDKs38qZjlbChSqFRXP/gsayaDuj47YWIm3zFRCGxOxPE7Lab9bqMWc2jQxNBSwOWmFTb8D/jqZ5SV2rZiKhghR0LRoTmjc6SVOiiPVoIoZkXhfjtqpyXgYdYGHyq3rBsuxlatNrZAOc5JUUwRwlAGSbdQb9FY06sw+KEkyyzljTtTGIaB1jtiEQiyGoRN/McuQc6Rva0eW4Cfuz2z9Jd+35fU5cOnxymwMsCiFKodFZoRR1Cbl+LwbncYzvHkYKDZKyscvgGQTxfoN1a1gn42xZWNZzeavaRlFH/Jc=
    file: reddit-notifier-*.tgz
    on:
      repo: kbirger/reddit-notifier
      branch: master
      tags: true
    skip_cleanup: 'true'
